### PR TITLE
Update to v0.14.1 PS

### PR DESCRIPTION
**Pull request by JordanMartinez**
Builds off of #56 and updates dependencies (pending merge of PRs), so that this builds on v0.14.1

### CODE REVIEW

**Comment by srghma** [comment]
@paluh

**Comment by i-am-the-slime** [comment]
Thanks @srghma and @JordanMartinez , I'll use this!

**Comment by JordanMartinez** [comment]
Closing this PR. I won't delete my branch for now because others might be using it.

**Comment by paluh** [comment]
Thanks a lot @JordanMartinez and @srghma and sorry for this huge delay... I'm not sure if I'm able to make a proper release now though :-(

**Pull request merged**
