### PR TITLE
WIP: Avoid `UnhandledPromiseRejectionWarning` on integrity errors

### LINKED ISSUE #24: `UnhandledPromiseRejectionWarning` on integrity errors
`src/Database/PostgreSQL.js` has this:
```javascript
                var q = client.query({
                        text: sql,
                        values: values,
                        rowMode: 'array',
                    }).catch(function(err) {
                        onError(err);
                    }).then(function(result) {
                        onSuccess(result.rows);
                    });
```
The `catch` and `then` handlers are in such an order that `then` is called even if an error was thrown, and as such `result` is `undefined` so `result.rows` throws an error. As a consequence, upon integrity error this is logged to console:
```
(node:23941) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'rows' of undefined
    at .../output/Database.PostgreSQL/foreign.js:43:42
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:23941) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23941) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The fix seems to be to change the code to have `then` before `catch`. I'm just wondering whether they are in that order for a reason?

### PR DESCRIPTION
**Pull request by akheron**
Fixes #24

### CODE REVIEW

**Comment by akheron** [comment]
Work in progress: There's no test to check that `UnhandledPromiseRejectionWarning` doesn't occur. `process.on('unhandledRejection', ...)` can be used to detect unhandled rejections, but it's not pretty.

**Comment by paluh** [comment]
@akheron Sorry for delay. I hope that I find to work on this library on weekend and make a new release.

**Comment by akheron** [comment]
No problem :)

**Comment by paluh** [comment]
I'm going to try to work on it now and publish minor release together with `command` addition...

**Pull request merged**
